.travis.yml, bin/cli.js, lib/xml.js, test/xml-test.js
The motivation for this commit is to have a module which we can build
upon and also to not expose out choice of xml parser so we can change it
if required later.
=> add xml module

lib/html.js, test/html-test.js
wrapping the mustache call with a promise
=> build: attempt to fix the build

lib/html.js
=> src: using mustache render instead to_html

bin/cli.js, package.json
=> src: configured and lint fix on bin/cli.js

bin/cli.js, lib/whitelist.js, test/whitelist-test.js
This commit renames the licenses property to license to be consistent
with the property in a project.json.
=> src: rename licenses property to license (#10)

bin/cli.js, lib/warnings.js, test/warnings-test.js
The warnings are placed in a separated module. Out of cli.js
=> #32 - Warnings into the new module

package-lock.json, package.json
license-checker 13.0.1 has a bug fix related to license file order
more details see: https://github.com/davglass/license-checker/issues/112
=> src: dependency update with bug fix

bin/cli.js, lib/file-reader.js, test/file-reader-test.js, test/fixtures/license/node_modules/sample_dependency_license/LICENSE
=> src: function extraction and tests added

bin/cli.js, bin/licenser
Also split function responsibility on cli.js
in some way Connects to #32
=> src: fix lint on licenser file

README.md
docs updated to use szero and genet projects.
=> doc: readme updated

lib/version-handler.js
=> fix: bug with regex versions

lib/listchecker.js
=> fix: dual license issue

bin/cli.js, lib/version-handler.js
Also removing unnecessary console.log
Connects to #57
=> src: display warning when no node_modules found

bin/cli.js
=> fix: copy the missing licenses.css file

bin/cli.js, lib/xml.js, test/xml-test.js
This PR has some goals:
1. To make more easy for me to understand some parts.
2. Part of #48 
3. To help with #69 and #68 
A brief description of this PR would be:
1. Modification of attribute names and functions that conflicted a bit with names from another "universe of
use".
2. Extraction of functions
3. Some redundancy reduction
4. Some line comments added
=> src: code style

bin/cli.js
=> src: version range warning message

README.md, bin/cli.js, bin/licenser, lib/resources/default-unifiedlist.json, lib/unifiedlist.js
=> src: maybe experimental implementation of the unified approved licenses list check

lib/unknown.js, test/unknown-test.js
This reverts commit 20f1173f82d998de67a4dc940b7983f08aac20b2.
=> Revert "src: mark custom license as UNKNOWN"

lib/unifiedlist.js
This is another case of #88, see that PR for more info and explanation.
=> 🐛 Output headings to stdout for consistency

lib/unifiedlist.js, test/unifiedlist-test.js
=> Improve unit test for unifiedlist

lib/resources/template.html, test/html-test.js
=> fix: updating the test and template to the new format.

bin/license-reporter
=> fix: bug with default canonical file location

bin/cli.js, bin/license-reporter
=> src: option to choose external css file

README.md
=> doc: how liceses are found in files

README.md
=> doc: Readme updated with new version

bin/cli.js
=> fix: node mudules not found

bin/cli.js
=> src: add project metadata when no node_modules found

README.md, bin/cli.js, bin/license-reporter
=> src: flag --metadata to add info about current project

lib/unified-list.js, test/unified-list-test.js
=> src: Return UNKNOWN for the url if is is not matched

lib/file-writer.js
=> src: file writer functions extracted from cli.js

test/file-writer-test.js
Connects to #149 
Missing test for mergeXMLs for now.
=> src: tests to create XML and HTML

package.json, test/file-writer-test.js
=> fix: build failure

test/file-writer-test.js
=> src: test merge xmls

lib/json-validator.js, package-lock.json, package.json, test/json-validator-test.js
=> src: json validation function for unified list

bin/cli.js, bin/license-reporter, lib/unified-list.js, test/unified-list-test.js
=> src: use an external unified-list

README.md
=> doc: about unified-list usage

lib/file-writer.js
=> src: file option will have always a .xml extension

lib/unified-list.js, test/unified-list-test.js
=> src: reenable unit test

bin/cli.js
=> fix: TypeError, we need always to 'init' unified list

bin/cli.js
=> fix: data duplication to the output.

README.md
=> doc: about the warnings and unknown value for licenses

README.md, bin/cli.js, bin/license-reporter, lib/file-writer.js, package-lock.json, package.json, test/file-writer-test.js
Note: the --file option now is --xml
Connects to #82
=> src: generating json and yaml

lib/canonical-name.js, package-lock.json
=> src: temporary fix for dual license cases

bin/cli.js, lib/file-writer.js
=> src: copy the license files to license directory

bin/cli.js, lib/file-writer.js
=> chore: move function that checks node_modules existence

bin/cli.js, lib/file-writer.js, lib/resources/template.html, test/file-writer-test.js
=> src: Local Licenses column on the HTML report

lib/file-writer.js, lib/resources/template.html, test/html-test.js
=> src: fix html links

lib/file-writer.js
=> fix: bug with URL not working on google-chrome

bin/cli.js, lib/file-writer.js, test/file-writer-test.js
=> src: files centralized inside licenses directory

bin/cli.js, lib/file-writer.js
=> fix: bug with file not found and bad file names

lib/file-writer.js, test/file-writer-test.js
=> src: unit test for create json function

lib/file-writer.js, test/file-writer-test.js
=> src: unit test for create yaml function

lib/unified-list.js
=> src: print warning for unknown list

README.md
Adding this for clarity from #202 in particular for OSX users. As the solution is OS specific I am linking to an informative StackOverflow thread which gives a lot of clarifications.
=> Updated Readme around EMFile issues on OSX

README.md
=> doc: using raincatcher-server as example

lib/canonical-name.js, lib/dual.js, lib/file-writer.js
=> src: duplicate in case of dual license

lib/dual.js, test/dual-test.js
Due refactor of dual.js by using function
expressions instead named functions.
=> Add unit tests to dual.js functions.

lib/file-reader.js, lib/remote-license.js, package-lock.json, package.json, test/file-reader-test.js, test/remote-license-test.js
The responsibility of file-reader.js is only
read files. A separeted function was created
to get the content of the license.
=> Add more unit tests and increate code reading.

package.json
Because we need to increase our coverage to avoid bugs.
=> Add a check for 90% code coverage.

bin/cli.js, lib/file-reader.js, test/file-reader-test.js
We don't need to check if the file exists
and we don't need to lookup remote file
for every time we call the function
that reads the file.
Also the code was cleaned a bit.
=> src: Increase performance and cleanup the code.

lib/unified-list.js, test/unified-list-test.js
=> src: code reuse and cleanup.

bin/cli.js, lib/messages.js, lib/unified-list.js, lib/version-handler.js, test/messages-test.js
Unified-list don't needs to be responsible
to print custom messages.
=> src: move custom messages to messages.js

bin/cli.js, lib/file-writer.js, lib/license-dependency.js, lib/project.js, test/project-test.js
Was created two new concepts:
* project
* license-dependency
Each one will handle things specific from project
and license+dependency.
The work is not done yet, but it will help a lot
with tests in a soon future.
=> src: Removes a lot of responsibility from cli.js

package-lock.json, package.json
=> fix: nyc downgrade to get coverage working again

bin/cli.js, lib/license-dependency.js, test/license-dependency-test.js, test/project-test.js
=> src: removes more code from cli.js

bin/license-reporter, lib/file-reader.js, lib/file-writer.js, lib/messages.js, lib/unified-list.js, lib/util.js, package.json, test/file-writer-test.js, test/project-test.js
=> src: more refactor

lib/file-writer.js, lib/license-dependency.js
=> src: fixes remaining issues from dual license

lib/modules/console.mdl.js, lib/modules/messages.js, lib/modules/report.mdl.js
Connects to #207 
Also part of #226 (warning messages)
=> src: shows dependencies using npm range version

lib/modules/report.mdl.js
=> src: feature added again, related with file not found on report

lib/commands/console.cmd.js, lib/commands/report.cmd.js, lib/commands/save.cmd.js, lib/modules/console.mdl.js, lib/modules/messages.js, lib/modules/report.mdl.js, lib/modules/unified-list.js, lib/modules/validator.js, test/lib/unified-list-test.js
Also the unified list validator was improved to validate the number of attributes.
Connects to #226
=> src: validation messages added

lib/commands/console.cmd.js, lib/commands/report.cmd.js, lib/commands/save.cmd.js, lib/modules/validator.js
=> fix: bug when no dependencies found.

lib/commands/console.cmd.js, lib/commands/report.cmd.js, lib/commands/save.cmd.js, lib/utils/validator.js, package-lock.json, package.json, test/lib/validator-test.js
=> src: using node-project-validator dependency

bin/cli.js, bin/license-reporter, index.js, lib/commands/console.cmd.js, lib/modules/console.mdl.js
=> src: flag to hide warning messages to console command

bin/cli.js, bin/license-reporter, lib/commands/console.cmd.js, lib/commands/merge.cmd.js, lib/commands/report.cmd.js, lib/commands/save.cmd.js, lib/utils/license-dir.js, package-lock.json, test/lib/save.mdl-test.js
Also using commandDir from yargs and
discarding cli.js modifying the command builder approach
=> src: removing duplicated code

bin/license-reporter, package-lock.json, package.json
=> fix: issue with yargs help

lib/commands/report.cmd.js, lib/utils/license-dir.js
=> src: removes all licenses before report command

package-lock.json, package.json
=> chore: removing unused dependency

.travis.yml, package-lock.json
This pull request resolves #289
=> remove node6xx from travis build

lib/commands/merge.cmd.js, lib/commands/report.cmd.js, lib/commands/save.cmd.js, lib/modules/merge.mdl.js, lib/modules/report.mdl.js, lib/modules/save.mdl.js, lib/utils/license-dir.js, test/lib/save.mdl-test.js
=> src: custom output directory option

.nsprc, package-lock.json
=> chore: remove .nsprc license-checker dep was fixed and released

package-lock.json
I ran npm audit fix to fix all audit issues.
Re-ran tests which seemed to still seemed to work.
14 test suites passed and 39 tests passed.
=> chore: fix vulnerabilities with npm audit fix

index.js, lib/commands/console.cmd.js, lib/commands/report.cmd.js, lib/commands/save.cmd.js, lib/modules/merge.mdl.js, lib/modules/report.mdl.js
@helio-frota I changed as many promises to async-await as I could find. #360 
The only file I left unchanged is the **lib/utils/xml.js** because I can't fully follow the way promises are used there.
=> Moving promises to async-await

.github/workflows/nodejs-ci-action.yml, package-lock.json, package.json, test/lib/checker.test.js
This is to keep same node versions accross nodeshift org
=> chore: add node 10.x and 14.x to build matrix

package-lock.json, package.json
This follows https://github.com/nodeshift/new-module-starter/#commit-messages
=> chore: adding standard-version
