nodeshift/license-reporter

- .travis.yml
There are currently no test so we are just skipping this for the time
being.
> remove npm test from .travis.yml

- README.md
I did not realize licenser was already a package. Just changing the link
for now.
> rename npm package name link

- bin/cli.js
- lib/licenses.css
- lib/template.html
- test/html-test.js
Currently the template is just a basic mustache example to verify that
the iteration of licenses was done properly. This commit adds a proper
html template using an example of a real Red Hat license html.
> src: update html template with Red Hat html

- README.md
- bin/cli.js
- bin/licenser
- lib/xml.js
- package-lock.json
- package.json
- test/xml-test.js
To motivation for this commit is to be able to merge multiple
license.xml files for individual projects. For products that include
multiple projects this will allow for the creation of a single xml that
includes all the subproject licenses.
> src: add xml merging support (#6)

- bin/cli.js
sample output 
```
<license>
<name>roi</name>
<version>0.15.0</version>
<license>Apache-2.0</license>
<file>/home/hf/d/szero/node_modules/roi/README.md</file>
</license>
```
> src: linking to the README instead parse it

- CONTRIBUTING.md
- README.md
- bin/cli.js
- bin/license-reporter
- package.json
This commit follows up on the renaming of the github repository to be
named license-reporter instead of licenser. The issue with the name
licenser was a name clash of an already existing npm module.
> rename module to license-reporter

- package.json
I missed the bin file which is still licenser which causes that name to
be installed as the binary executable when published.
I've also updated the version as I've already published 0.1.0.
> change the name of the binary file

- lib/unknown.js
- package-lock.json
- test/unknown-test.js
Currently if a project specifies multiple licenses as an array the
following error will be reported:
```console
return value === undefined || value === '' || value.toUpperCase() ===
unknown;
^
TypeError: value.toUpperCase is not a function
at check
(/bucharest-gold/license-reporter/lib/unknown.js:37:55)
at unknownCheck
(/bucharest-gold/license-reporter/lib/unknown.js:21:10)
at project.licenses.license.filter
(/bucharest-gold/license-reporter/lib/unknown.js:8:9)
at Array.filter (native)
at Object.module.exports.check
(/bucharest-gold/license-reporter/lib/unknown.js:6:35)
at Test.test
(/bucharest-gold/license-reporter/test/unknown-test.js:20:48)
at Test.bound [as _cb]
(/bucharest-gold/license-reporter/node_modules/tape/lib/test.js:64:32)
at Test.run …
```
> src: support arrays of licenses in license field

- lib/unknown.js
- test/unknown-test.js
We have gotten feedback on the output of a custom license which simply
contains a link to the project in question. The request was to mark
such licenses as unknown instead.
> src: mark custom license as UNKNOWN

- README.md
- bin/cli.js
- bin/license-reporter
- test/xml-test.js
Currently, the entire license is include in the xml. This functionality
is preserved but with a flag named verbose. The default is false in
which case only the path to the license will be included in the produced
xml.
Fixes: https://github.com/bucharest-gold/license-reporter/issues/92
> src: add verbose option to include entire license

- lib/whitelist.js
- test/whitelist-test.js
Currently unknown license will also be included in the non-whitelisted
list causing them to be reported twice (also in the unknown list that
his).
This commit excludes unkown license from the whitelist.
Fixes: https://github.com/bucharest-gold/license-reporter/pull/96
> src: don't include unknown licenses in whitelist

- lib/unifiedlist.js
Currently, the warning message for approved/not approved licenses does
not line up with any unknown licenses found making the output look
sloppy.
This commit makes the headers consistent.
> src: make approved warnings message consistent

- README.md
- bin/cli.js
- bin/license-reporter
- lib/canonical-name.js
- lib/file-reader.js
- package-lock.json
- package.json
- test/canonical-name-test.js
- test/file-reader-test.js
This commit allows license names to be renamed using by specifing a
mapping file containing a mapping of the license name to a canonical
name.
> src: support canonical license name mapping

- bin/cli.js
- bin/license-reporter
- lib/canonical-name.js
- lib/resources/default-canonicalnames.json
- lib/unifiedlist.js
- test/canonical-name-test.js
- test/unifiedlist-test.js
Instead of using the absolute file url to the license file this commit
uses the url specified in the unifiedlist.json.
This commit also adds a default canonical names mapping file so that one
is not required to be specified on the command line. This is just a
default and can be overridden using the --namemap options as the command
line.
Closes: #110
> src: use license url instead of file path

- lib/unifiedlist.js
- test/unifiedlist-test.js
There is currently a bug when trying to map a license name to a url does
not accept a comma separated list of names. This can happen when using a
deprecated license property in package.json.
This commit adds a check and reports any urls found.
Closes: #124
> src: support array of names for urlForName

- lib/unified-list.js
- package-lock.json
- package.json
- test/unified-list-test.js
Currently there are a few functions that are only exported for testing
purposes. This commit suggests using rewire in the unit test and remove
the exported functions.
> src: reduce functions exported by unified-list

- package.json
See https://docs.npmjs.com/misc/scripts#prepublish-and-prepare for a
detailed explanation.
Without this change, if there are any vulnerabilities found by `nsp
check`, then users can't install this module, without using
`--ignore-scripts`.
> Use prepublishOnly instead of prepublish

- lib/file-writer.js
Changed the output directory to be licenses to avoid a collision with the common term LICENSE which appears in a lot of projects.
> fixed problem with licenses directory to avoid collisions

- lib/file-reader.js
- lib/file-writer.js
- package.json
Connects to #202 
I can't reproduce this on fedora. Seems to be a MacOS issue.
> bug: fix ENFILE: file table overflow by using graceful-fs module

- package.json
Seems that  --check-coverage --lines
args are affecting the coverage report.
This PR is to check if this is true.
> fix: check if  nyc arguments affects the coverage report

- lib/modules/report.mdl.js
In the `projectMetaData` that the report command hands to the report
module, it's possible that the `licenses.license.name` field is an
array, such as for `rc@0.4.0`:
```json
"dependencies": {
"dependency": [
{
"packageName": "rc",
"version": "0.4.0",
"licenses": {
"license": [
{
"name": [
"BSD",
"MIT",
"Apache2"
],
"url": "UNKNOWN"
}
]
},
"file": "RC_BSD,MIT,APACHE2.TXT"
}
]
}
```
In this case, there won't be a `.split` function on it.
I'm not sure if this is the best way to do this or not.
> 🐛 Handle names as array in report module

- lib/modules/report.mdl.js
- lib/modules/resources/template.html
- test/lib/html-test.js
These are 2 things that I figured a PR was an easier way to
propose/discuss, rather than creating an issue to get your feeling
about them. Below are the commit messages:
```
🎨 Call it licenses.html instead of license.html
The xml and css (maybe others?) use the plural 'licenses.<extension>' in
their file names. This just changes the html file to match those.
```
and
```
🎨 Put packageName in "Package Artifact" col in html
Before this change, it would be in the "Package Group" column. I guess the
2 columns would map to a groupId and artifactId in maven. Given that we
don't have groupIds in npm dependencies, I think the name fits better in
the artifact column.
```
Let me know what you think!
> 🎨 Minor suggestions for file names and html output

- lib/commands/console.cmd.js
- lib/commands/report.cmd.js
- lib/commands/save.cmd.js
- lib/modules/checker.js
- test/lib/checker-test.js
This introduces an '--include-dev-dependencies' option to the console,
report, and save commands. The default behaviour changes here also to
include only production dependencies by default.
Fixes #241.
> 💥 Only include dev deps if option set

- lib/commands/merge.cmd.js
this happen when we call merge command inside a directory
that is not a Node.js project
Connects to #249
> fix: a bug when calling merge command
